services:
  storage:
    image: redis
    volumes:
      - ./data:/data
    networks:
    - app-network

  counter:
    image: antonchik/counter
    environment:
    - PORT=3001
    - REDIS_URL=redis://storage
    ports:
    - 81:3001
    depends_on:
    - storage
    networks:
      - app-network

  library:
    image: antonchik/library
    ports:
    - 80:3000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge